<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>DesktopSystemMonitor.Diagnostics</RootNamespace>
    <AssemblyName>DesktopSystemMonitor.Diagnostics</AssemblyName>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DesktopSystemMonitor.Core\DesktopSystemMonitor.Core.csproj" />
    <ProjectReference Include="..\DesktopSystemMonitor.Windows\DesktopSystemMonitor.Windows.csproj" />
  </ItemGroup>
</Project>
